In [1]:
import sys
sys.path.append(r"/home/zhangbw/Documents/projects/party/src/")
from party.vector import *

In [2]:
a = FourVector(3, 6, 9, 16, label='a')
a

a^u = [3.0, 6.0, 9.0, 16.0]

In [3]:
b = FourVector(100, 3, -4, -45, label='b')
b

b^u = [100.0, 3.0, -4.0, -45.0]

In [4]:
(b * a) * (a + b)

((a+b)x-438.0)^u = [-45114.0, -3942.0, -2190.0, 12702.0]

In [5]:
res, matrix = a.rotate(np.pi/6, 1)
print(res)
print(matrix)

rotate(a, axis=1, degree=30.000)^u = [3.0, 6.0, 15.79423, 9.35641]
[[ 1.         0.         0.         0.       ]
 [ 0.         1.         0.         0.       ]
 [ 0.         0.         0.8660254  0.5      ]
 [ 0.         0.        -0.5        0.8660254]]


In [6]:
res, matrix = a.rotate(np.pi/6, (1, 0, 0))
print(res)
print(matrix)

rotate(a, axis=(1, 0, 0), degree=30.000)^u = [3.0, 6.0, 7.79423, 9.35641]
[[ 1.         0.         0.         0.       ]
 [ 0.         1.         0.         0.       ]
 [ 0.         0.         0.8660254  0.       ]
 [ 0.         0.        -0.5        0.8660254]]


In [7]:
res, matrix = b.boost(-0.5, 3)
print(res)
print(matrix)

boost(b, axis=3, velocity=-0.500)^u = [89.48929, 3.0, -4.0, 5.7735]
[[1.15470054 0.         0.         0.57735027]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.57735027 0.         0.         1.15470054]]


In [8]:
res, matrix = b.boost(-0.5, (0, 0, 1))
print(res)
print(matrix)

boost(b, axis=(0, 0, 1), velocity=-0.500)^u = [89.48929, 3.0, -4.0, 5.7735]
[[1.15470054 0.         0.         0.57735027]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.57735027 0.         0.         1.15470054]]


In [9]:
res, matrix = b.boost_to_zmf()
print(res)
print(matrix)

boost(b, axis=(0.03, -0.04, -0.45), velocity=0.453)^u = [89.16277, 0.0, -0.0, 0.0]
[[ 1.12154431e+00 -3.36463292e-02  4.48617723e-02  5.04694939e-01]
 [-3.36463292e-02  1.00053361e+00 -7.11478877e-04 -8.00413737e-03]
 [ 4.48617723e-02 -7.11478877e-04  1.00094864e+00  1.06721832e-02]
 [ 5.04694939e-01 -8.00413737e-03  1.06721832e-02  1.12006206e+00]]
