In [1]:
import sys
sys.path.append(r"/home/zhangbw/Documents/projects/party/src/")
from party.vector import *

In [2]:
a = FourVector(10, 1, 1, 1, label='a')
a

a^u = [10.0, 1.0, 1.0, 1.0]

In [3]:
b = FourVector(10, -1, 1, -1, label='b')
b

b^u = [10.0, -1.0, 1.0, -1.0]

In [4]:
c = FourVector(5, 0, 0, 5, label='c')
c * c, c.square()

(0.0, 0.0)

In [5]:
(b * a) * (a + b)

((a+b)x101.0)^u = [2020.0, 0.0, 202.0, 0.0]

In [6]:
res, matrix = a.rotate(np.pi/6, 1)
print(res)
print(matrix)

rotate(a, axis=1, degree=30.000)^u = [10.0, 1.0, 1.36603, 0.36603]
[[ 1.         0.         0.         0.       ]
 [ 0.         1.         0.         0.       ]
 [ 0.         0.         0.8660254  0.5      ]
 [ 0.         0.        -0.5        0.8660254]]


In [7]:
res, matrix = a.rotate(np.pi/6, (1, 0, 0))
print(res)
print(matrix)

rotate(a, axis=(1, 0, 0), degree=30.000)^u = [10.0, 1.0, 0.86603, 0.36603]
[[ 1.         0.         0.         0.       ]
 [ 0.         1.         0.         0.       ]
 [ 0.         0.         0.8660254  0.       ]
 [ 0.         0.        -0.5        0.8660254]]


In [8]:
res, matrix = b.boost(-0.5, 3)
print(res)
print(matrix)

boost(b, axis=3, velocity=-0.500)^u = [10.96966, -1.0, 1.0, 4.6188]
[[1.15470054 0.         0.         0.57735027]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.57735027 0.         0.         1.15470054]]


In [9]:
res, matrix = b.boost(-0.5, (0, 0, 1))
print(res)
print(matrix)

boost(b, axis=(0, 0, 1), velocity=-0.500)^u = [10.96966, -1.0, 1.0, 4.6188]
[[1.15470054 0.         0.         0.57735027]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.57735027 0.         0.         1.15470054]]


In [10]:
res, matrix = b.boost_to_zmf()
print(res)
print(matrix)

boost(b, axis=(-0.1, 0.1, -0.1), velocity=0.173)^u = [9.84886, 0.0, -0.0, 0.0]
[[ 1.01534617  0.10153462 -0.10153462  0.10153462]
 [ 0.10153462  1.00511539 -0.00511539  0.00511539]
 [-0.10153462 -0.00511539  1.00511539 -0.00511539]
 [ 0.10153462  0.00511539 -0.00511539  1.00511539]]


In [11]:
-b, b.opposite()

((bx-1)^u = [-10.0, 1.0, -1.0, 1.0], b^u = [10.0, 1.0, -1.0, 1.0])